version: "2"

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: disable

linters:
  enable:
    - errorlint
    - unconvert
    - unparam
  exclusions:
    generated: disable
    presets:
      - comments
      - std-error-handling
