dist: bionic
os: linux
language: minimal
cache:
  directories:
  - /home/travis/.vagrant.d/boxes
jobs:
  include:
    - name: "Fedora 32"
      before_install:
        - sudo .ci/install-vagrant.sh
        - ln -sf .ci/Vagrantfile.fedora32 Vagrantfile
        - sudo vagrant up && sudo mkdir -p /root/.ssh && sudo sh -c "vagrant ssh-config >> /root/.ssh/config"
      script:
        - sudo ssh default -t 'cd /vagrant && sudo make'
