on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.22.x, 1.23.x]
        platform: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, windows-latest, macos-12, macos-14]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Find go.sum files
      id: gosum
      shell: bash
      run: |
        echo 'files<<EOF' >> "$GITHUB_OUTPUT"
        git ls-files '*/go.sum' >> "$GITHUB_OUTPUT"
        echo 'EOF' >> "$GITHUB_OUTPUT"
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: ${{ steps.gosum.outputs.files }}
    - name: Set PACKAGES env
      if: ${{ matrix.go-version == '1.18.x' }}
      run: |
        # This corresponds with the list in Makefile:1, but omits the "userns"
        # and "capability" modules, which require go1.21 as minimum.
        echo 'PACKAGES=mountinfo mount sequential signal symlink user' >> $GITHUB_ENV
    - name: go mod tidy
      run: |
        make foreach CMD="go mod tidy"
        git diff --exit-code
    - name: go fix
      run: |
        make foreach CMD="go fix"
        git diff --exit-code
    - name: Lint
      run: make lint
    - name: Cross build
      if: ${{ runner.os == 'Linux' }}
      run: make cross
    - name: Test
      run: |
        uname -a
        make test

